services:
  kong:
    build: .
    container_name: kong-gateway
    env_file:
      - .env
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      # Tell Kong to load your custom plugins
      KONG_LOG_LEVEL: debug
      KONG_PLUGINS: bundled,jwt-claims-headers,api-gateway-secret
      # Pass environment variables from the .env file
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
      CLUB_SERVICE_URL: ${CLUB_SERVICE_URL}
      EVENT_SERVICE_URL: ${EVENT_SERVICE_URL}
      NOTIFY_SERVICE_URL: ${NOTIFY_SERVICE_URL}
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    volumes:
      # This volume is no longer strictly necessary if you use the ENV var for the key,
      # but it doesn't hurt to leave it.
      - ./auth_public_key.pem:/etc/kong/auth_public_key.pem:ro